#pragma once

#include <string>
#include <fstream>
#include <optional>

#ifndef TRACE
#ifdef ENABLE_TRACE
// Trace is enabled, return the value it is given
#define TRACE(...) __VA_ARGS__
#else
// Trace is disabled - enable it by defining ENABLE_TRACE in the build system
#define TRACE(...)
#endif
#endif

namespace soct::logging {

    /// The different log levels
    enum log_level_t {
        TRACE(TRACE1 = 9,)
        DEBUG = 10,
        INFO = 11,
        WARN = 12,
        ERR = 13,
        ANY = 14
    };

    /// Global variables and functions
    namespace globals {
        /// The global log level (default: INFO)
        extern log_level_t log_level;

        /// Whether to dump all output to the console (useful for debugging)
        extern bool all2console;


        /// The log file stream
        extern std::optional<std::ofstream> log_stream;

        inline constexpr std::string_view debug_prefix = "[DEBUG]";
        inline constexpr std::string_view info_prefix = "[INFO]";
        inline constexpr std::string_view warning_prefix = "[WARN]";
        inline constexpr std::string_view error_prefix = "[ERROR]";

        // Constants based on the debug messages generated by rocket-chip
        inline constexpr size_t rocket_chip_message_len = 147;
        inline constexpr size_t rocket_chip_dasm_start = 137; // The start of the disassembly message
        inline constexpr size_t rocket_chip_dasm_len = 8;
    }


    ///@brief  Returns the current state of the global flag for logging to a file
    bool is_log_file_enabled();

    ///@brief  Sets the global log level
    void set_log_level(log_level_t level);

    ///@brief Initializes the log file
    void init_logging(const std::string& file = "log.txt");

    ///@brief Closes the log file
    void close_logging();

    ///@brief Checks if the log file is open
    bool is_log_file_open();

    /// Checks if the given message is from a RocketChip core that is being logged (configured in soct::log_cores). Checks if string starts with C<core_id>
    bool is_rocketchip_log(const std::string_view& s);

    /// Extracts the disassembly message from a RocketChip core log message
    std::string_view get_rocket_chip_dasm(const std::string_view& s);

    ///@brief  Checks if the given message is a debug message
    bool is_debug_msg(const std::string_view& s);

    ///@brief  Checks if the given message is an info message
    bool is_info_msg(const std::string_view& s);

    ///@brief  Checks if the given message is a warning message
    bool is_warning_msg(const std::string_view& s);

    ///@brief  Checks if the given message is an error message
    bool is_error_msg(const std::string_view& s);

    ///@brief Checks if the given message is within the current log level
    bool prefix_within_log_level(const std::string_view& s, log_level_t level = static_cast<log_level_t>(globals::log_level));

    /// Parses log level from a string ("trace", "debug", "info", "warn", "err", "any")
    log_level_t parse_log_level(std::string_view s);

    /// A simple logger class that can be used to log messages to the console or a file
    class logger_t {
    public:
        explicit logger_t(const log_level_t& level,
                          const std::string_view& prefix = "",
                          bool log_to_file = false,
                          bool log_to_console = true);

        void flush() const;

        /// Initializes the progress bar with a prefix and suffix. You can then update the progress bar with the update_progress_bar function
        void init_progress_bar(const std::string& prefix, const std::string& suffix);

        void update_progress_bar(const auto progress) {
            if (m_pb_prefix.has_value() && m_pb_suffix.has_value() && m_log_to_console) {
                m_console_out << "\033[2K" << "\033[G" << m_prefix << m_pb_prefix.value() << progress << m_pb_suffix.value() << std::flush;
            }
        }

        void close_progress_bar();

        template <typename T>
        logger_t& operator<<(const T& value) {
            if (within_log_level()) {
                if (m_log_to_file && is_log_file_enabled()) {
                    pipe_to_stream(globals::log_stream.value(), value);
                }
                if (m_log_to_console) {
                    pipe_to_stream(m_console_out, value);
                }
            }
            return *this;
        }

        using manipulator_t = std::ostream& (*)(std::ostream&);

        logger_t& operator<<(const manipulator_t manip) {
            if (within_log_level()) {
                if (m_log_to_file && is_log_file_enabled()) {
                    globals::log_stream.value() << manip;
                }
                if (m_log_to_console) {
                    manip(m_console_out);
                }
            }
            return *this;
        }

    private:
        template <typename ST, typename VT>
        auto pipe_to_stream(ST& stream, VT value) -> decltype(stream << value) {
            if (m_prefix.empty()) {
                return stream << value;
            }
            const char* str_data = nullptr;

            if constexpr (std::is_same_v<VT, char> || std::is_same_v<VT, const char>) {
                if (value == '\n') {
                    m_prepend_prefix = true;
                }
            } else if constexpr (std::is_same_v<VT, std::string> || std::is_same_v<VT, const std::string>) {
                str_data = value.c_str();
            } else if constexpr (std::is_same_v<VT, std::string_view> || std::is_same_v<VT, const std::string_view>) {
                str_data = value.data();
            } else if constexpr (std::is_same_v<VT, char*> || std::is_same_v<VT, const char*>) {
                str_data = value;
            } else {
                return stream << value;
            }

            if (str_data == nullptr) { return stream << value; }

            while (true) {
                const char next = *str_data++;
                if (next == '\0') {
                    break;
                }
                if (m_prepend_prefix) {
                    stream << m_prefix;
                    m_prepend_prefix = false;
                }
                if (next == '\n') {
                    m_prepend_prefix = true;
                    stream << next;
                } else {
                    stream << next;
                }
            }
            return stream;
        }

        /// The current log level
        const log_level_t m_level;

        /// The prefix for the log message
        const std::string m_prefix;

        /// Whether to log to a file
        const bool m_log_to_file;

        /// Whether to log to the console
        const bool m_log_to_console;

        /// The stream to log to
        std::ostream& m_console_out;

        /// Whether to print the prefix before the next character in the stream
        bool m_prepend_prefix = true;

        /// The prefix for the progress bar
        std::optional<std::string> m_pb_prefix = std::nullopt;

        /// The suffix for the progress bar
        std::optional<std::string> m_pb_suffix = std::nullopt;

        /// Checks if the level of the message is within the current log level
        [[nodiscard]] bool within_log_level() const;
    };

    namespace elf {
        // Color green
        extern logger_t to_stderr;
        extern logger_t to_stdout;
    }

    namespace rocketchip {
        // No color
        extern logger_t console;
        extern logger_t file;
    }

    namespace circuit {
        // Color yellow
        extern logger_t console;
        extern logger_t file;
    }

    namespace fesvr {
        // Trace has color blue
        TRACE(extern logger_t trace;)
        // The rest have color cyan
        extern logger_t debug;
        extern logger_t info;
        extern logger_t warn;
        extern logger_t error;
    }
}
