package soct.system.vivado.components

import org.chipsalliance.cde.config.Parameters
import soct.system.vivado.SOCTBdBuilder
import soct.system.vivado.abstracts._

/**
 * Xilinx AXI4-Stream to Video Out: converts the framebuffer pixel stream into parallel video
 * (data + sync + data-enable), aligned to the timing generated by a
 * [[VideoTimingController]]. The parallel side runs in the pixel clock domain; the built-in
 * async FIFO crosses from the stream clock.
 * Documentation: https://docs.amd.com/r/en-US/pg044_v_axis_vid_out
 *
 * The parallel output is wired pin-by-pin (not as a `vid_io` interface) because the ZynqMP
 * PS exposes its DP live video input as individual pins.
 */
case class AxisVideoOut()(implicit bd: SOCTBdBuilder, p: Parameters)
  extends BdComp with Xip with ConnectOps {

  override def partName: String = "xilinx.com:ip:v_axi4s_vid_out:4.0"

  override def defaultProperties: Map[String, String] = Map(
    "CONFIG.C_HAS_ASYNC_CLK" -> "1", // stream clock and pixel clock are unrelated
    // Master timing mode: the core gates the timing generator through vtg_ce and releases
    // it at a frame boundary once its FIFO is primed, which guarantees output lock. This is
    // the mode the vtg_ce -> gen_clken wiring implements; the IP default is slave, which
    // consumes the stream without ever locking when fed from a free-running VDMA.
    "CONFIG.C_VTG_MASTER_SLAVE" -> "1"
  )

  /** Pixel stream from the VDMA */
  object VIDEO_IN extends BdIntfPin("video_in", AxisVideoOut.this)

  /** Timing from the [[VideoTimingController]] */
  object VTIMING_IN extends BdIntfPin("vtiming_in", AxisVideoOut.this)

  /** Stream-side clock/enable/reset */
  object ACLK extends BdPinIn("aclk", AxisVideoOut.this)

  object ACLKEN extends BdPinIn("aclken", AxisVideoOut.this)

  object ARESETN extends BdPinIn("aresetn", AxisVideoOut.this)

  /** Pixel-side clock/enable/reset */
  object VID_IO_OUT_CLK extends BdPinIn("vid_io_out_clk", AxisVideoOut.this)

  object VID_IO_OUT_CE extends BdPinIn("vid_io_out_ce", AxisVideoOut.this)

  object VID_IO_OUT_RESET extends BdPinIn("vid_io_out_reset", AxisVideoOut.this)

  /** Parallel video out (individual pins, towards the PS DP live video input) */
  object VID_ACTIVE_VIDEO extends BdPinOut("vid_active_video", AxisVideoOut.this)

  object VID_DATA extends BdPinOut("vid_data", AxisVideoOut.this)

  object VID_HSYNC extends BdPinOut("vid_hsync", AxisVideoOut.this)

  object VID_VSYNC extends BdPinOut("vid_vsync", AxisVideoOut.this)

  /** Timing-generator clock enable - drives the [[VideoTimingController]]'s gen_clken */
  object VTG_CE extends BdPinOut("vtg_ce", AxisVideoOut.this)

  /** Output lock: the stream is aligned to the timing and video is leaving the core */
  object LOCKED extends BdPinOut("locked", AxisVideoOut.this)

  /** Stream FIFO ran empty mid-frame (pixel-rate underrun) */
  object UNDERFLOW extends BdPinOut("underflow", AxisVideoOut.this)

  /** Stream FIFO overflowed (upstream faster than the pixel rate accepts) */
  object OVERFLOW extends BdPinOut("overflow", AxisVideoOut.this)
}
