package soct.system.vivado

import scala.collection.mutable


/**
 * Tcl variable with description and default value
 *
 * @param description Description of the variable
 * @param default     Default value of the variable
 */
final case class TclVar(description: String, default: String)


class SOCTBdVars {
  // Map of variable names to their descriptions and default values
  val vars: mutable.Map[String, TclVar] = mutable.Map.empty

  /**
   * Static map of block design specific TCL variables that are instantiated in the BD script.
   */
  val bdVars: mutable.Map[String, TclVar] = mutable.Map.empty

  /**
   * Add a block design TCL variable
   *
   * @param name        The name, INCLUDING the dereferencing $
   * @param description A description of the variable
   * @param default     The default value of the variable
   */
  def addBdVar(name: String, description: String, default: String): Unit = {
    bdVars += (name -> TclVar(description, default))
  }


  def genTCLHeader(vars: Map[String, TclVar]): String = {
    val varDecls = vars.map { case (v, TclVar(description, default)) =>
      // Strip the leading $ from the variable name
      val varName = v.stripPrefix("$")
      s"""
         |# $varName: $description
         |if {[info exists $varName] == 0} {set $varName "$default"}""".stripMargin
    }.mkString("\n") + "\n"

    s"""# Auto-generated Vivado TCL script
       |# Generated by SOCT
       |
       |# Header with variable descriptions - modify as needed
       |$varDecls""".stripMargin
  }
}

object SOCTBdVars {

  // Keys for TCL variables
  object k {
    final val aggressive = "$aggressive"
    final val sources = "$sources"
    final val constraints = "$constraints"
    final val synth = "$synth"
    final val impl = "$impl"
    final val projectName = "$project_name"
    final val bdName = "$bd_name"
    final val xilinxPart = "$xilinx_part"
    final val partName = "$part_name"
    final val sourcesDir = "$sources_dir"
    final val vivadoProjectDir = "$vivado_project_dir"
    final val defaultBdGenerator = "$default_bd_generator"
    final val defaultSynthGenerator = "$default_synth_generator"
    final val defaultImplGenerator = "$default_impl_generator"
    final val xdcDir = "$xdc_dir"
    final val nThreads = "$n_threads"
  }
}
