cmake_minimum_required(VERSION 3.20)

# The SOCT System provides many variables used throughout the build process.
if (DEFINED SOCT_SYSTEM)
    cmake_path(IS_ABSOLUTE SOCT_SYSTEM _is_abs)
    if (NOT _is_abs)
        message(FATAL_ERROR "SOCT_SYSTEM variable must be an absolute path to a valid SOCTSystem.cmake file. Current value: ${SOCT_SYSTEM}")
    endif ()
    if (NOT EXISTS "${SOCT_SYSTEM}")
        message(FATAL_ERROR "SOCT_SYSTEM points to a file that does not exist: ${SOCT_SYSTEM}. Has the system been (re)generated?")
    endif ()
    message(STATUS "Using SOCT system file from SOCT_SYSTEM variable: ${SOCT_SYSTEM}")
else ()
    cmake_path(GET CMAKE_CURRENT_LIST_DIR PARENT_PATH _temp)
    cmake_path(GET _temp PARENT_PATH _soceteer_root)
    cmake_path(APPEND _soceteer_root "SOCTSystem-latest.cmake" OUTPUT_VARIABLE _latest_soct_system) # Hardcoded fallback name (symlink) that SoCeteer creates for the latest system file

    if (NOT EXISTS "${_latest_soct_system}")
        message(FATAL_ERROR "SOCT_SYSTEM variable not defined or file not found, and fallback latest SOCT system file not found at ${_latest_soct_system}. Have you emitted a SoC system file from SoCeteer?")
    else ()
        file(REAL_PATH "${_latest_soct_system}" _latest_soct_system_real)
        message(WARNING "SOCT_SYSTEM variable not defined - falling back to the latest generated system: ${_latest_soct_system_real}. Pass -DSOCT_SYSTEM=<path> to select a system explicitly.")
        set(SOCT_SYSTEM "${_latest_soct_system}")
    endif ()
endif ()

# Consumer projects call this right after include(${SOCT_SYSTEM}) with the minimum
# SoCeteer version whose system files they understand, mirroring cmake_minimum_required:
# SOCETEER_VERSION is stamped into every generated system file from the release version,
# so a stale workspace stops the configure here - with regeneration named as the fix -
# instead of failing later on a missing or misread variable. A version the comparison
# cannot order (e.g. "unknown", from a build without version metadata) fails the check.
function(soct_minimum_required)
    cmake_parse_arguments(_soct_min "" "VERSION" "" ${ARGN})
    if (NOT DEFINED _soct_min_VERSION OR DEFINED _soct_min_UNPARSED_ARGUMENTS)
        message(FATAL_ERROR "soct_minimum_required: usage is soct_minimum_required(VERSION <x.y.z>)")
    endif ()
    if (NOT DEFINED SOCETEER_VERSION)
        message(FATAL_ERROR "The system file ${SOCT_SYSTEM} does not define SOCETEER_VERSION. Regenerate the workspace with the current SoCeteer.")
    endif ()
    if (SOCETEER_VERSION VERSION_LESS _soct_min_VERSION)
        message(FATAL_ERROR "The system file ${SOCT_SYSTEM} was generated by SoCeteer ${SOCETEER_VERSION}, but this project requires at least ${_soct_min_VERSION}. Regenerate the workspace with the current SoCeteer.")
    endif ()
endfunction()
