cmake_minimum_required(VERSION 3.20)

# The SOCT System provides many variables used throughout the build process.
if (DEFINED SOCT_SYSTEM)
    cmake_path(IS_ABSOLUTE SOCT_SYSTEM _is_abs)
    if (NOT _is_abs)
        message(FATAL_ERROR "SOCT_SYSTEM variable must be an absolute path to a valid SOCTSystem.cmake file. Current value: ${SOCT_SYSTEM}")
    endif ()
    message(STATUS "Using SOCT system file from SOCT_SYSTEM variable: ${SOCT_SYSTEM}")
else ()
    cmake_path(GET CMAKE_CURRENT_LIST_DIR PARENT_PATH _temp)
    cmake_path(GET _temp PARENT_PATH _soceteer_root)
    cmake_path(APPEND _soceteer_root "workspace" OUTPUT_VARIABLE _soceteer_workspace)
    cmake_path(APPEND _soceteer_root "test_run_dir" "workspace" OUTPUT_VARIABLE _soceteer_test_workspace)

    if (NOT EXISTS "${_soceteer_workspace}" AND NOT EXISTS "${_soceteer_test_workspace}")
        message(FATAL_ERROR "Neither ${_soceteer_workspace} nor ${_soceteer_test_workspace} directories exist. Please ensure that you have built a SoCeteer project to generate the SOCT system file or set the SOCT_SYSTEM variable to point to a valid SOCTSystem.cmake file.")
    endif ()

    message(WARNING
            "SOCT_SYSTEM variable not defined or file not found.
     This variable should point to a valid SOCTSystem.cmake file generated by SoCeteer.
     The SOCTSystem.cmake file contains important information about the SoC configuration which will be used during the build process and to build the target binaries.
     (Fallback) Locating the LATEST emitted SOCT system file from ${_soceteer_workspace} and ${_soceteer_test_workspace}.")
    file(GLOB_RECURSE SOCT_SYSTEM_FILES CONFIGURE_DEPENDS "${_soceteer_workspace}/**/SOCTSystem.cmake" "${_soceteer_test_workspace}/**/SOCTSystem.cmake")

    if (SOCT_SYSTEM_FILES)
        set(_latest_soct "")
        set(_latest_ts 0)
        foreach (_file IN LISTS SOCT_SYSTEM_FILES)
            # Get last modification timestamp (UTC, seconds since epoch)
            file(TIMESTAMP "${_file}" _ts "%s" UTC)
            if (_ts GREATER _latest_ts)
                set(_latest_ts "${_ts}")
                set(_latest_soct "${_file}")
            endif ()
        endforeach ()
        message(STATUS "Using latest SOCT system file: ${_latest_soct}")
        set(SOCT_SYSTEM "${_latest_soct}")
    else ()
        message(FATAL_ERROR "No SOCTSystem.cmake file found in ${_soceteer_workspace}. Please ensure that a SoCeteer project has been built to generate the SOCT system file or set the SOCT_SYSTEM variable to point to a valid SOCTSystem.cmake file.")
    endif ()
endif ()