/*
 * gemmini-detect - object detection on the monitor: digits are localized in a
 * scene by sliding the shared MNIST classifier (shared/mnist, running its
 * matmuls on Gemmini) across it, and the detections are drawn as labeled
 * bounding boxes through soctfb.
 *
 * The scene (scene.h) is generated by shared/mnist/generate.py --scene: a float
 * canvas in the model's own normalization for inference, a grayscale copy for
 * display, and the ground truth for the accuracy report. Windows whose ink
 * mass is near the background are skipped before inference - most of the
 * canvas is empty, and an empty window can only misfire. Overlapping
 * detections are reduced by confidence-ordered non-maximum suppression.
 */
#include <stdio.h>

#include "mnist_common.h"
#include "model.h"
#include "scene.h"
#include "soctdt.h"
#include "soctfb.h"

/* The model is an MLP - no translation invariance at all, a few pixels of
 * misalignment collapse its confidence. The stride must therefore be fine and
 * the centering gate tight; the gate is arithmetic only and runs before the
 * accelerator, so the fine scan stays cheap. */
#define STRIDE 2u
/* Confidence a window must reach (the model's final layer is a softmax, so its
 * outputs are probabilities); sliding a pure classifier over a scene misfires
 * confidently on partial digits, so the bar is high and NMS cleans up the
 * rest. */
#define CONF_MIN 0.90f
/* Minimum ink (sum over background, in full-ink pixel equivalents) for a
 * window to be worth inferring. */
#define INK_MIN 40.0f
/* The classifier is confident on off-center crops too (a half-visible digit
 * scores high, usually as a round-ish 0), so confidence cannot reject them.
 * The ink centroid can: only windows holding their ink near the center are
 * classified - those are the in-distribution crops the model was trained on. */
#define CENTER_MAX_OFF 2.0f
#define MAX_CANDIDATES 256
#define NMS_MAX_OVERLAP 0.1f

typedef struct {
    unsigned short x, y;
    unsigned char label;
    float conf;
    float probs[MNIST_CLASSES];
} detection;

static detection s_cand[MAX_CANDIDATES];
static unsigned s_ncand;
static detection s_kept[MAX_CANDIDATES];
static unsigned s_nkept;

static void enable_fpu(void) {
    uint64_t mstatus;
    asm volatile("csrr %0, mstatus" : "=r"(mstatus));
    mstatus |= 0x6000; /* FS = dirty: FP instructions on */
    asm volatile("csrw mstatus, %0" ::"r"(mstatus));
}

/* Ink mass of a window plus the centroid of that mass (window coordinates). */
static float window_ink(unsigned wx, unsigned wy, float *cx, float *cy) {
    float ink = 0.0f, mx = 0.0f, my = 0.0f;
    for (unsigned r = 0; r < MNIST_HEIGHT; r++) {
        const float *row = &scene_norm[(size_t) (wy + r) * SCENE_W + wx];
        for (unsigned c = 0; c < MNIST_WIDTH; c++) {
            const float v = row[c] - SCENE_BG;
            ink += v;
            mx += v * (float) c;
            my += v * (float) r;
        }
    }
    if (ink > 0.0f) {
        *cx = mx / ink;
        *cy = my / ink;
    } else {
        *cx = *cy = 0.0f;
    }
    return ink / SCENE_SPAN;
}

static float classify(unsigned wx, unsigned wy, unsigned *label, float *probs) {
    static elem_t in[1][MNIST_PIXELS];
    static elem_t out[1][MNIST_CLASSES];

    for (unsigned r = 0; r < MNIST_HEIGHT; r++) {
        const float *row = &scene_norm[(size_t) (wy + r) * SCENE_W + wx];
        for (unsigned c = 0; c < MNIST_WIDTH; c++) {
            in[0][r * MNIST_WIDTH + c] = (elem_t) row[c];
        }
    }
    entry(in, out);

    /* The model's final layer is a softmax: out[] are probabilities. */
    unsigned best = 0;
    for (unsigned i = 0; i < MNIST_CLASSES; i++) {
        probs[i] = (float) out[0][i];
        if (out[0][i] > out[0][best]) best = i;
    }
    *label = best;
    return probs[best];
}

/* Intersection over union of two window-sized boxes. */
static float iou(const detection *a, const detection *b) {
    const int dx = (int) a->x - (int) b->x;
    const int dy = (int) a->y - (int) b->y;
    const int ox = MNIST_WIDTH - (dx < 0 ? -dx : dx);
    const int oy = MNIST_HEIGHT - (dy < 0 ? -dy : dy);
    if (ox <= 0 || oy <= 0) return 0.0f;
    const float inter = (float) ox * (float) oy;
    return inter / (2.0f * MNIST_WIDTH * MNIST_HEIGHT - inter);
}

static void nms(void) {
    /* Selection sort by confidence - the candidate count is small. */
    for (unsigned i = 0; i + 1 < s_ncand; i++) {
        unsigned best = i;
        for (unsigned j = i + 1; j < s_ncand; j++) {
            if (s_cand[j].conf > s_cand[best].conf) best = j;
        }
        const detection t = s_cand[i];
        s_cand[i] = s_cand[best];
        s_cand[best] = t;
    }
    /* A suppressed candidate is the same digit seen a pixel or two shifted -
     * for a translation-sensitive model, its probabilities are an independent
     * vote, not noise. Fold them into the surviving box and relabel from the
     * average: an ensemble over shifts, at zero extra inference cost. */
    s_nkept = 0;
    for (unsigned i = 0; i < s_ncand; i++) {
        int merged = 0;
        for (unsigned j = 0; j < s_nkept; j++) {
            if (iou(&s_cand[i], &s_kept[j]) > NMS_MAX_OVERLAP) {
                for (unsigned k = 0; k < MNIST_CLASSES; k++) {
                    s_kept[j].probs[k] += s_cand[i].probs[k];
                }
                merged = 1;
                break;
            }
        }
        if (!merged) s_kept[s_nkept++] = s_cand[i];
    }
    for (unsigned j = 0; j < s_nkept; j++) {
        float sum = 0.0f;
        unsigned best = 0;
        for (unsigned k = 0; k < MNIST_CLASSES; k++) {
            sum += s_kept[j].probs[k];
            if (s_kept[j].probs[k] > s_kept[j].probs[best]) best = k;
        }
        s_kept[j].label = (unsigned char) best;
        s_kept[j].conf = sum > 0.0f ? s_kept[j].probs[best] / sum : 0.0f;
    }
}

int main(void) {
    enable_fpu();
    printf("=== gemmini-detect: sliding the MNIST model over a %ux%u scene ===\n",
           SCENE_W, SCENE_H);

    soctfb fb;
    soctfb_init(&fb);

    /* The scene, integer-upscaled and centered; boxes draw in scene
     * coordinates times the same scale. */
    unsigned scale = fb.width / SCENE_W;
    if (fb.height / SCENE_H < scale) scale = fb.height / SCENE_H;
    if (!scale) scale = 1;
    const unsigned ox = (fb.width - SCENE_W * scale) / 2;
    const unsigned oy = (fb.height - SCENE_H * scale) / 2;

    soctfb_fill(&fb, 0, 0, fb.width, fb.height, 0x181820);
    soctfb_blit_gray_scaled(&fb, ox, oy, SCENE_W, SCENE_H, scene_gray, scale);
    soctfb_text(&fb, ox, oy > 24 ? oy - 24 : 0, "GEMMINI-DETECT: SCANNING...", 0xFFFFFF);
    soctfb_flush_all(&fb);

    /* Slide. */
    const unsigned long t0 = cycles_now();
    unsigned inferred = 0, skipped = 0, offcenter = 0;
    const float mid_x = (MNIST_WIDTH - 1) / 2.0f, mid_y = (MNIST_HEIGHT - 1) / 2.0f;
    for (unsigned wy = 0; wy + MNIST_HEIGHT <= SCENE_H; wy += STRIDE) {
        for (unsigned wx = 0; wx + MNIST_WIDTH <= SCENE_W; wx += STRIDE) {
            float cx, cy;
            if (window_ink(wx, wy, &cx, &cy) < INK_MIN) {
                skipped++;
                continue;
            }
            const float dx = cx - mid_x, dy = cy - mid_y;
            if (dx > CENTER_MAX_OFF || dx < -CENTER_MAX_OFF ||
                dy > CENTER_MAX_OFF || dy < -CENTER_MAX_OFF) {
                offcenter++;
                continue;
            }
            unsigned label;
            float probs[MNIST_CLASSES];
            const float conf = classify(wx, wy, &label, probs);
            inferred++;
            if (conf >= CONF_MIN && s_ncand < MAX_CANDIDATES) {
                detection *d = &s_cand[s_ncand++];
                d->x = (unsigned short) wx;
                d->y = (unsigned short) wy;
                d->label = (unsigned char) label;
                d->conf = conf;
                for (unsigned k = 0; k < MNIST_CLASSES; k++) d->probs[k] = probs[k];
            }
        }
    }
    nms();
    const unsigned long us = cycles_to_us(cycles_now() - t0);

    /* Report and draw. */
    printf("windows: %u inferred, %u empty, %u off-center; %u candidates -> %u detections "
           "in %lu.%03lu s (%lu us/inference)\n",
           inferred, skipped, offcenter, s_ncand, s_nkept, us / 1000000, (us / 1000) % 1000,
           inferred ? us / inferred : 0);
    unsigned hits = 0;
    for (unsigned i = 0; i < s_nkept; i++) {
        const detection *d = &s_kept[i];
        printf("  (%u,%u): digit %u, %u.%u%%\n", d->x, d->y, d->label,
               (unsigned) (d->conf * 100), (unsigned) (d->conf * 1000) % 10);
        for (unsigned t = 0; t < SCENE_TRUTH_N; t++) {
            const int dx = (int) d->x - scene_truth[t].x;
            const int dy = (int) d->y - scene_truth[t].y;
            if (dx > -14 && dx < 14 && dy > -14 && dy < 14 &&
                d->label == scene_truth[t].label) {
                hits++;
                break;
            }
        }

        char tag[16];
        snprintf(tag, sizeof(tag), "%u %u%%", d->label, (unsigned) (d->conf * 100));
        const unsigned bx = ox + d->x * scale, by = oy + d->y * scale;
        soctfb_rect(&fb, bx, by, MNIST_WIDTH * scale, MNIST_HEIGHT * scale, 2, 0x00FF40);
        soctfb_text(&fb, bx, by > 18 ? by - 18 : by, tag, 0x00FF40);
    }
    printf("ground truth matched: %u/%u\n", hits, (unsigned) SCENE_TRUTH_N);

    /* Text draws only its set pixels; clear the old label's box first. */
    const unsigned label_y = oy > 24 ? oy - 24 : 0;
    soctfb_fill(&fb, ox, label_y, 28 * 8, 16, 0x181820);
    soctfb_text(&fb, ox, label_y, "GEMMINI-DETECT: DONE", 0xFFFFFF);
    soctfb_flush_all(&fb);
    for (;;) {
    }
}
