import random
import subprocess
from pathlib import Path
from typing import List
import argparse

NUM_IMAGES = 20
NUM_CLASSES = 10

IMAGE_PATHS_FN = "image_paths.txt"
LABELS_FN = "labels.bin"
MNIST_FT = ".bin"
MNIST_DIR = "mnist_samples"
DATA_DIR = "data"

this_dir: Path = Path(__file__).parent
mnist_dir = this_dir / MNIST_DIR
data_dir = this_dir / DATA_DIR

image_paths_path = data_dir / IMAGE_PATHS_FN
labels_path = data_dir / LABELS_FN


def copy_file(src: Path, dest: Path):
    with src.open("rb") as f:
        with dest.open("wb") as ff:
            ff.write(f.read())


def generate_new():
    assert mnist_dir.exists(), f"MNIST directory does not exist: {mnist_dir}"
    data_dir.mkdir(exist_ok=True, parents=True)

    # Clear data dir
    for file in data_dir.glob("*"):
        file.unlink()

    for digit in range(NUM_CLASSES):
        digit_dir = mnist_dir / str(digit)
        assert digit_dir.exists(), f"Missing digit dir: {digit_dir}"
        images_path = list(digit_dir.glob(f"*{MNIST_FT}"))
        assert len(images_path) >= NUM_IMAGES, f"Too few images in {digit_dir}"
        random.shuffle(images_path)
        images_path: List[Path] = images_path[:NUM_IMAGES]
        with image_paths_path.open("a") as f:
            with labels_path.open("ab") as ff:
                for image_path in images_path:
                    image_name = image_path.name
                    copy_file(image_path, data_dir / image_name)
                    f.write(str(image_name) + "\n")
                    ff.write(digit.to_bytes(1, byteorder="little"))

    with image_paths_path.open() as f:
        image_paths = f.readlines()
    with labels_path.open("rb") as f:
        labels = f.read()
    assert len(image_paths) == len(labels), \
        f"Number of images and labels do not match: {len(image_paths)} vs {len(labels)}"

    print("Done")


def generate_scene(out_path: Path, num_digits: int, width: int, height: int, seed):
    """A detection scene: digits from mnist_samples placed on a canvas, emitted as a
    C header (float canvas for inference, uint8 canvas for display, ground truth).
    The samples are raw float32 in whatever normalization the model was trained
    with; the canvas copies them verbatim and takes its background from a sample's
    corner pixel, so no normalization knowledge is needed here."""
    import array

    rng = random.Random(seed)
    d = 28  # MNIST_WIDTH/HEIGHT

    def load_sample(path: Path):
        a = array.array("f")
        a.frombytes(path.read_bytes())
        assert len(a) == d * d, f"{path}: expected {d * d} floats, got {len(a)}"
        return a

    picks = []
    for _ in range(num_digits):
        digit = rng.randrange(NUM_CLASSES)
        files = sorted((mnist_dir / str(digit)).glob(f"*{MNIST_FT}"))
        picks.append((digit, load_sample(rng.choice(files))))

    bg = picks[0][1][0]  # a corner pixel is always background
    canvas = [bg] * (width * height)

    def overlaps(x, y, boxes):
        return any(abs(x - bx) < d and abs(y - by) < d for bx, by, _ in boxes)

    truth = []
    for digit, sample in picks:
        for _ in range(1000):
            x = rng.randrange(0, width - d)
            y = rng.randrange(0, height - d)
            if not overlaps(x, y, truth):
                break
        else:
            raise SystemExit("could not place all digits - enlarge the canvas")
        for r in range(d):
            canvas[(y + r) * width + x:(y + r) * width + x + d] = sample[r * d:(r + 1) * d]
        truth.append((x, y, digit))

    lo, hi = min(canvas), max(canvas)
    span = (hi - lo) or 1.0
    gray = [int(255 * (v - lo) / span) for v in canvas]

    with out_path.open("w") as f:
        f.write("/* Generated by shared/mnist/generate.py --scene - do not edit. */\n")
        f.write(f"#define SCENE_W {width}\n#define SCENE_H {height}\n")
        f.write(f"#define SCENE_BG {bg!r}f\n#define SCENE_SPAN {span!r}f\n")
        f.write(f"#define SCENE_TRUTH_N {len(truth)}\n")
        f.write("static const struct { unsigned short x, y; unsigned char label; } "
                "scene_truth[SCENE_TRUTH_N] = {\n")
        for x, y, digit in truth:
            f.write(f"    {{{x}, {y}, {digit}}},\n")
        f.write("};\n")
        f.write("static const float scene_norm[SCENE_H * SCENE_W] = {\n")
        for i in range(0, len(canvas), 8):
            f.write("    " + ", ".join(f"{v!r}f" for v in canvas[i:i + 8]) + ",\n")
        f.write("};\n")
        f.write("static const unsigned char scene_gray[SCENE_H * SCENE_W] = {\n")
        for i in range(0, len(gray), 24):
            f.write("    " + ", ".join(str(v) for v in gray[i:i + 24]) + ",\n")
        f.write("};\n")
    print(f"Wrote {out_path}: {width}x{height}, {len(truth)} digits, bg={bg!r}")


def main():
    parser = argparse.ArgumentParser(description="Generate MNIST image/label dataset for baremetal inference.")
    parser.add_argument("--new", action="store_true", help="Generate a new set of MNIST images and labels. THIS WILL OVERWRITE EXISTING DATA.")
    parser.add_argument("--scene", type=Path, metavar="OUT_H",
                        help="Generate a detection scene header (digits scattered on a canvas) at OUT_H.")
    parser.add_argument("--scene-digits", type=int, default=6)
    parser.add_argument("--scene-size", type=str, default="256x192", metavar="WxH")
    parser.add_argument("--seed", type=int, default=None)
    args = parser.parse_args()

    if args.scene:
        w, h = (int(v) for v in args.scene_size.split("x"))
        generate_scene(args.scene, args.scene_digits, w, h, args.seed)
    elif args.new:
        generate_new()
    else:
        parser.print_help()


if __name__ == "__main__":
    main()