name: Tests (native)

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      chisel:
        required: true
        type: string
      test_script:
        required: true
        type: string

jobs:
  test-native:
    runs-on: ${{ inputs.os }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Enable long paths for Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
          git config --system core.longpaths true

      - name: Set and create test workspace (SOCT_TEST_RUN_DIR)
        run: |
          echo "SOCT_TEST_RUN_DIR=${{ runner.os == 'Windows' && 'D:\\t' || '/tmp/t' }}" >> $GITHUB_ENV
          mkdir -p "${SOCT_TEST_RUN_DIR}"


      - name: Checkout code with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK 22+
        uses: actions/setup-java@v5
        with:
          java-version: "22"
          distribution: temurin

      - name: Install sbt
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            curl -fLsS "https://github.com/coursier/coursier/releases/download/v2.1.24/cs-x86_64-pc-linux.gz" -o cs.gz \
            && gzip -d cs.gz \
            && chmod +x cs \
            && ./cs setup -y \
            && echo "${HOME}/.local/share/coursier/bin" >> $GITHUB_PATH
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            brew install sbt
          else
            choco install -y sbt
          fi

      - name: Install cmake and Ninja
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            sudo apt-get update
            sudo apt-get install -y cmake ninja-build
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            brew install cmake ninja
          else
            choco install -y cmake ninja
          fi

      - name: Install device tree compiler (DTC)
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            sudo apt-get install -y device-tree-compiler
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            brew install dtc
          else
            choco install -y dtc-msys2
          fi

      - name: Install flex and bison
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            sudo apt-get install -y flex bison libfl-dev
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            brew install flex bison
          else
            choco install -y winflexbison3
          fi

      - name: Run tests (native)
        env:
          SOCT_CHISEL_VERSION: ${{ inputs.chisel }}
        run: |
          chmod +x "${{ inputs.test_script }}"
          "${{ inputs.test_script }}"